caption_model: CTX
# noamopt: true
# noamopt_warmup: 50  # 原始是20000，对应batch_size 10
label_smoothing: 0.0
input_json: data/cocotalk.json
input_label_h5: data/cocotalk_label.h5
input_att_dir: data/cocobu_att

new_features: true
obj_dir: data/oscar.hdf5
grid_dir : data/vis_ctx.hdf5
tag_dir: data/txt_ctx.hdf5
tags_h5: data/tags_to_calculate.hdf5
topk: 12
tags_num: 100


seq_per_img: 5

learning_rate: 0.0001

num_layers: 3
input_encoding_size: 512
rnn_size: 2048

# Transformer config
N_enc: 3
N_dec: 3
d_model: 512
d_ff: 2048
num_att_heads: 8
dropout: 0.3


learning_rate_decay_start: 0
scheduled_sampling_start: 0



language_eval: 1
val_images_use: 5000

# 用于3090 * 3
#batch_size: 64
#save_checkpoint_every: 1000
#max_epochs: 25

# 用于A800 * 3
batch_size: 192
save_checkpoint_every: 250
max_epochs: 25

REFORWARD: false