_BASE_: DiM2T.yml
reduce_on_plateau: true
noamopt: false
# learning_rate: 0.00001
# learning_rate_decay_start: -1

learning_rate: 0.000005 # 5e-6
learning_rate_decay_start: -1

output_pkl: data/coco-train

self_critical_after: 20 # 应该设置15-20就够了

# 用于A800 * 3
batch_size: 48
save_checkpoint_every: 800
# 乘起来等于3W最好，相当于0.25个eboch保存一次


# 用于3090 * 3
#batch_size: 12
#save_checkpoint_every: 5000

train_sample_n: 5
max_lenth: 20

base_type: average # or greedy
base_range: avg

d_reduction: fc # or sample or conv

cider_reward_weight: 1
bleu_reward_weight: 0
cov_reward_weight: 1
cl_reward_weight: 0
cl_expected: 18

self_cider_reward_weight: 0 # 1


# structure_loss_weight: 1
# structure_loss_type: new_self_critical

max_epochs: 40